steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build", "-t", "us-central1-docker.pkg.dev/${PROJECT_ID}/rambam/botimage", "."
    ]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "push", "us-central1-docker.pkg.dev/${PROJECT_ID}/rambam/botimage"
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Fetching DJANGO_SECRET from Secret Manager..."
        echo "$(gcloud secrets versions access latest --secret="DISCORD_TOKEN")"
    id: Get gcloud secrets for testing purpose

  # Entrypoint, timeout and environment variables
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    timeout: 240s
    args:
      - '-c'
      - |
        gcloud compute instances update-container rambam-discord-bot \
        --container-image us-central1-docker.pkg.dev/${PROJECT_ID}/rambam/botimage \
        --container-env TOKEN=$DISCORD_TOKEN
    env:
      - "CLOUDSDK_COMPUTE_REGION=us-central1"
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
    secretEnv: ["DISCORD_TOKEN"]


options:
    logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/DISCORD_TOKEN/versions/latest
    env: "DISCORD_TOKEN"
